version: "2"

services:
    web:
        build: .
        ports:
            - "4000:4000"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"